### ISSUE TITLE
[acpi-cpufreq] Frequency adjusting sliders should fit Performance and Powersave governors behaviour

### ISSUE THREAD

**Issue by terencode** [konkor/cpufreq#14] opened 2017-03-01 22:17 UTC
When *Performance* govenor is selected, the minimum frequency scaling option should be disabled; when *Powersave* govenor is selected, the maximum frequency scaling option should be disabled.

**Comment by konkor** [comment] 2017-03-02 08:09
"It's not a bug It's a feature" lol
Yeah It can seem strange but u can set minimum frequency for _powersafe_ mode and maximum for _performance_ mode like in _userspace_ mode. Same behavior has intel_pstate driver: 2 modes only _powersafe_, _performance_ and possibility to change min/max frequencies in percentages...

**Comment by konkor** [comment] 2017-03-02 08:11
But now i see other problem here. Initializing _powersafe_ mode should set minimum frequency and _performance_ - max.

**Comment by terencode** [comment] 2017-03-02 09:35
Ahah well changing maximum frequency for *Performance* makes sense but I don't see the use of setting the minimum as by definition it will always stay at the highest frequency.

**Comment by terencode** [comment] 2017-03-02 09:36
Same thought for *powerwave* but with maximum frequency.

**Comment by RicardoEPRodrigues** [comment] 2017-03-06 01:11
For the `intel_pstate`, the _powersave_ mode doesn't **stay** in the minimum, it **prefers** the minimum.

Basically when you need more CPU _powersave_ will give you more clockwork, while _performance_ will try to always stay in maximum frequency.

**Comment by konkor** [comment] 2017-03-06 05:23
**RicardoEPRodrigues** _intel_pstate powersave_ mode is an analog of _acpi_cpufreq ondemand_ mode. Actually intel doesnt have classic powersave mode at all. And if you want constantly minimum freq You have to set minimum and frequencies to minimum physical available frequency. So the extension reads default values from intel_pstate driver after governors changing.

**Comment by konkor** [comment] 2017-03-06 05:43
Governors aren't just Names for some profiles. They have own behavior in states changing (timings, state sequence, CPU loading coefficients). U can google more about this. Basic difference between intel_pstate and acpi is intel controls a behavior of governors inside of CPU and ACPI modes on kernel.

**Comment by konkor** [comment] 2017-03-06 05:53
Actually a changing of governors don't save too much CPU power bcs only changing of Voltage on motherboard can really save some power. But CPU can eat less power (I - amperes) in IDLE state it's why Intel made powersave governor dynamic. If CPU is without loading CPU takes less Power. So if CPU makes jobs quicker and goes to IDLE state it's eating less Power...

**Comment by konkor** [comment] 2017-03-06 06:37
So I can't see any practical usage of any other governors. Only dynamic OnDemand (or Conservative for ACPI driver) and Powersave (for intel_pstate) with minimum and maximum available frequencies can reduce some power consuming in real world. U can reduce maximum but time to make some CPU jobs going longer so it's cause bigger power consuming.

**Comment by konkor** [comment] 2017-04-23 11:52
@terencode It's time to close this issue :)

**Closed** 2017-04-24 08:04 UTC

**Comment by terencode** [comment] 2017-04-24 16:27
@konkor sorry I sent it from the mobile phone and it did not send thanks for closing it.

**Comment by konkor** [comment] 2017-04-24 17:47
@terencode it's ok. but i completely forget about _intel_pstate_mode_ behavior there is 2 modes only _performance_ , _powersave_ and both dynamic. It's why i didn't want to fix this. There is no clear way to set sensitivity for gnome-shell popupmenu widgets...
