### ISSUE TITLE
About changing settings.

### ISSUE THREAD

**Issue by stiletto009** [konkor/cpufreq#56] opened 2018-01-28 13:17 UTC
Hi i started using cpufreq couple minutes ago. whenever i try to change governor settings from panel like max/min freq turbo boost etc. it applies for the other one as well. for example i edited powersave as %10 min 2 cores turbo off but when i change to performance mode it still stays. i also tried creating custom preference but it didnt help. i use ubuntu 17.10 irqbalance disabled pstate enabled and its fresh install.

thanks.

**Comment by konkor** [comment] 2018-01-29 16:05
@stiletto009 thank you for the report. Unfortunately, I don't have intel_pstate hardware now. I'll try to fix it soon if it's possible. Maybe this related to #39 issue. Actually, you can't change minimum frequency percentage less than physical available minimum frequency on some governors and configurations.
Can you give a bit more information about it?
Are you switching to the new performance configuration through a custom profile or UI?
PS: You could try acpi_cpufreq mode as a temporary solution by disabling intel_pstate mode (see README.md).

**Comment by stiletto009** [comment] 2018-02-02 06:44
i mean im switching betweeen settings but whenever i do the previous one is lost.remember settings is on.

**Comment by konkor** [comment] 2018-02-02 17:19
@stiletto009 you are right. There was an issue in the loading remembered settings sequence on intel_pstate mode.
You can test it from the github master branch. So you can use custom profiles to avoid this issue and to have cores switching supporting via profiles. The simple `Remember settings` don't allow you to save all cpu parameters like cores power and mixed modes where is separated cores could have different governors and frequencies.

**Thank you for the report**

_I don't know what's going on with extensions.gnome.org but it looks like there is no maintainer 2 months... heh_

**Comment by konkor** [comment] 2018-02-28 18:24
Updating for the issue is available everywhere including Gnome repo now. So I'm closing it.

**Closed by konkor** 2018-02-28 18:24 UTC
