### ISSUE TITLE
New menu instantly closes after clicking on the extension indicator.

### ISSUE THREAD

**Issue by Shished** [konkor/cpufreq#98] opened 2019-04-06 14:57 UTC
OS: openSUSE Tumbleweed
Gnome-shell 3.30

When clicking on the extension indicator i can see the top window flickering and no extension menu opened. Sometimes it opens for a moment and closes.
The workaround is to click on other extensions indicator, slide mouse to this extension and click on it, in this way it opens properly.

**Comment by konkor** [comment] 2019-04-06 15:15
@Shished I can't reproduce it but I will try to test it on openSUSE.

There is no menu now. 1st click on extension button is launching Gtk main application in extension mode (without close button). 2nd click is closing that app window.

So I think It could be broken mouse. Sometimes it happens with old mouses they produce 2 clicks on single tap. You could check it in the GNOME Control Settings->Devices->Mouse & Touchpad->Test Your Settings.

Alternatively, you could create a desktop shortcut directly to the _~/.local/share/gnome-shell/extensions/cpufreq@konkor/cpufreq-application_ 

Thank you for the report! I will consider to add _Disable extension mode_ option for the GNOME Extension to avoid such behaviour.

**Comment by konkor** [comment] 2019-04-07 09:35
@Shished I think I found an elegant solution to this issue in the commit https://github.com/konkor/cpufreq/commit/ff1c3db7395b86791b595e4936cda49cffcfb1b1 I made delay in 1 sec between clicks in the extension mode.

**Comment by gombosg** [comment] 2019-04-11 14:44
Same here on F29 GNOME 3.30, strange workaround works.

**Comment by sungoku** [comment] 2019-04-27 08:08
Ubuntu18.04 with Gnome shell 3.28.3 still have this problem, I tried web install, git source install, all the same.
"The workaround is to click on other extensions indicator, slide mouse to this extension and click on it, in this way it opens properly."   -------  Only this workaround could use.
But, when switch to Wayland, the UI just fine. Why??

**Comment by Shished** [comment] 2019-04-27 08:19
I upgraded gnome to 3.32 and no longer have this problem.

**Comment by ksuhiyp** [comment] 2019-05-04 19:17
Same issue here, here is journal ctl output 

May 04 22:17:01 idea pkexec[21624]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
May 04 22:17:01 idea pkexec[21624]: idea: Executing command [USER=root] [TTY=unknown] [CWD=/home/idea] [COMMAND=/usr/bin/cpufreqctl irqbalance]
May 04 22:17:01 idea pkexec[21634]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
```
May 04 22:17:01 idea pkexec[21634]: idea: Executing command [USER=root] [TTY=unknown] [CWD=/home/idea] [COMMAND=/usr/bin/cpufreqctl turbo 0]
May 04 22:17:01 idea pkexec[21641]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
May 04 22:17:01 idea pkexec[21641]: idea: Executing command [USER=root] [TTY=unknown] [CWD=/home/idea] [COMMAND=/usr/bin/cpufreqctl turbo 0]
May 04 22:17:01 idea gjs[9582]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 04 22:17:01 idea gjs[9582]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
May 04 22:17:01 idea gjs[9582]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

```

**Comment by gombosg** [comment] 2019-05-05 21:10
Problem persists on F30, GNOME 3.32

**Comment by SX91** [comment] 2019-06-24 12:29
Same here, Ubuntu 19.04. GNOME Shell 3.32.0, latest plugin version.
I only see OS POWER logo, then it disappears.

**Comment by konkor** [comment] 2019-06-25 12:04
You can disable **Extension Mode** in the _Preferences_ window.

BTW: I still can't reproduce such behaviour on my tested configurations. It could be an extension or even driver issue. Something is picking focus away when the main application is starting.

So can you disable all other extensions, restart GNOME session and turn them back one by one to help find the cause?

**Comment by qakcn** [comment] 2019-07-23 05:05
> Same here, Ubuntu 19.04. GNOME Shell 3.32.0, latest plugin version.
> I only see OS POWER logo, then it disappears.

Same issue before, and now the main window closes immediately after upgraded to latest version.
There is a way to open it, first click on other indicator such as system monitor, and click on cpufreq, the main window will remain opened now.

**Comment by konkor** [comment] 2019-10-13 18:13
If you have issues with auto-closing or other similar issues, You can disable _Extension Mode_ in the _Preferences_ window.
![Screenshot from 2019-10-13 21-08-25](https://user-images.githubusercontent.com/1944781/66719883-27664280-edfe-11e9-812c-d86b8f82a144.png)

**Closed by konkor** 2019-10-13 18:13 UTC
Labels: done, duplicate, needs info
